
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

public class AccountManager_Surface extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AccountManager_Surface.class.getName());

    private int userID;
    private String username;
    private String role;

    public AccountManager_Surface(int userID, String username, String role) {
        this.userID = userID;
        this.username = username;
        this.role = role;

        initComponents();
        this.setLocationRelativeTo(null);

        //Sets the size to be untangleable and in fixed size
        this.setResizable(false);
        this.setMinimumSize(new java.awt.Dimension(500, 450));
        this.setMaximumSize(new java.awt.Dimension(500, 450));
        this.setPreferredSize(new java.awt.Dimension(500, 450));

        this.setTitle("Account Manager");

        loadUserData();

        applyTheme();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        lblAccountManager = new javax.swing.JLabel();
        LOGO = new javax.swing.JLabel();
        lblHello_Acc = new javax.swing.JLabel();
        pnlSide = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblWhatRole = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblWhatGender = new javax.swing.JLabel();
        lblBirthdate = new javax.swing.JLabel();
        lblWhatBirthdate = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        pnlAccountInfo = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblAccountInfo = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        pnlPasswordInfo = new javax.swing.JPanel();
        lblPasswordInfo = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        chckbtnShowPassword = new javax.swing.JCheckBox();
        btnChangePassword = new javax.swing.JButton();
        btnReturnToDashboard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 450));
        setMinimumSize(new java.awt.Dimension(500, 450));
        setPreferredSize(new java.awt.Dimension(500, 450));
        setSize(new java.awt.Dimension(500, 450));

        lblAccountManager.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblAccountManager.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAccountManager.setText("Account Settings");

        LOGO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGO.setText("LOGO");

        lblHello_Acc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHello_Acc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHello_Acc.setText("Hello - [user]");
        lblHello_Acc.setToolTipText("");

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHello_Acc, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAccountManager, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LOGO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlTopLayout.createSequentialGroup()
                        .addComponent(lblAccountManager)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(lblHello_Acc)))
                .addContainerGap())
        );

        getContentPane().add(pnlTop, java.awt.BorderLayout.PAGE_START);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("[user]");

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        lblWhatRole.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblWhatRole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWhatRole.setText("Admin/User");

        lblGender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGender.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGender.setText("Gender");

        lblWhatGender.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblWhatGender.setText("MALE/FEMALE");

        lblBirthdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBirthdate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBirthdate.setText("Birthdate");

        lblWhatBirthdate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblWhatBirthdate.setText("MM-DD-YYYY");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("PERSONAL INFO");

        javax.swing.GroupLayout pnlSideLayout = new javax.swing.GroupLayout(pnlSide);
        pnlSide.setLayout(pnlSideLayout);
        pnlSideLayout.setHorizontalGroup(
            pnlSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideLayout.createSequentialGroup()
                .addGroup(pnlSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWhatRole, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlSideLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addComponent(lblGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblWhatGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBirthdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblWhatBirthdate, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(jSeparator2))))
                .addContainerGap())
            .addGroup(pnlSideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSideLayout.setVerticalGroup(
            pnlSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblWhatRole, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWhatGender, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWhatBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pnlSide, java.awt.BorderLayout.LINE_START);

        pnlMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pnlAccountInfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsername.setText("Username");

        lblAccountInfo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAccountInfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAccountInfo.setText("ACCOUNT INFO");

        txtUsername.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUsername.setText("username");

        javax.swing.GroupLayout pnlAccountInfoLayout = new javax.swing.GroupLayout(pnlAccountInfo);
        pnlAccountInfo.setLayout(pnlAccountInfoLayout);
        pnlAccountInfoLayout.setHorizontalGroup(
            pnlAccountInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccountInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAccountInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAccountInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUsername)
                    .addGroup(pnlAccountInfoLayout.createSequentialGroup()
                        .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlAccountInfoLayout.setVerticalGroup(
            pnlAccountInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccountInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAccountInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlPasswordInfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lblPasswordInfo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPasswordInfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPasswordInfo.setText("PASSWORD INFO");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPassword.setText("Current password");

        txtPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPassword.setText("password");

        chckbtnShowPassword.setText("Show Password");
        chckbtnShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckbtnShowPasswordActionPerformed(evt);
            }
        });

        btnChangePassword.setText("Change Password");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPasswordInfoLayout = new javax.swing.GroupLayout(pnlPasswordInfo);
        pnlPasswordInfo.setLayout(pnlPasswordInfoLayout);
        pnlPasswordInfoLayout.setHorizontalGroup(
            pnlPasswordInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPasswordInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPasswordInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPasswordInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPassword)
                    .addGroup(pnlPasswordInfoLayout.createSequentialGroup()
                        .addComponent(lblPassword)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlPasswordInfoLayout.createSequentialGroup()
                        .addComponent(chckbtnShowPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(btnChangePassword)))
                .addContainerGap())
        );
        pnlPasswordInfoLayout.setVerticalGroup(
            pnlPasswordInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPasswordInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPasswordInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPasswordInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chckbtnShowPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChangePassword))
                .addContainerGap())
        );

        btnReturnToDashboard.setText("Return to Dashboard");
        btnReturnToDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnToDashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPasswordInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAccountInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnReturnToDashboard)))
                .addContainerGap())
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAccountInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlPasswordInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnReturnToDashboard)
                .addContainerGap())
        );

        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to log out?",
                "Confirm Log-Out",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            dispose();
            new LogIn_Surface().setVisible(true);
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        javax.swing.JPasswordField newPasswordField = new javax.swing.JPasswordField();
        javax.swing.JPasswordField confirmPassword = new javax.swing.JPasswordField();

        Object[] message = {
            "New Password:", newPasswordField,
            "Confirm Password:", confirmPassword
        };

        int option = JOptionPane.showConfirmDialog(this,
                message,
                "Confirm Password",
                JOptionPane.OK_CANCEL_OPTION);

        if (option != JOptionPane.OK_OPTION) {
            return;
        }

        String newPassword = new String(newPasswordField.getPassword()).trim();
        String confirmNewPassword = new String(confirmPassword.getPassword()).trim();

        if (newPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Password cannot be empty.",
                    "Warning",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (newPassword.length() < 6) {
            JOptionPane.showMessageDialog(this,
                    "Password must be at least 6 characters.",
                    "Weak Password",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!newPassword.equals(confirmNewPassword)) {
            JOptionPane.showMessageDialog(this,
                    "Passwords do not match. Please try again.",
                    "Mismatch",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        String sql = "UPDATE users SET password = ? WHERE id = ?";
        Connection connect = DatabaseConnection.getConnection();

        if (connect == null) {
            JOptionPane.showMessageDialog(this,
                    "Cannot connect to database.",
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (PreparedStatement statement = connect.prepareStatement(sql)) {
            statement.setString(1, newPassword);
            statement.setInt(2, userID);
            statement.executeUpdate();

            JOptionPane.showMessageDialog(this,
                    "Password changed successfully!",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (SQLException e) {
            logger.severe("Change password error: " + e.getMessage());

            JOptionPane.showMessageDialog(this,
                    "Error changing password: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnReturnToDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnToDashboardActionPerformed
        dispose();
        new HomeworkTrackerSystem(userID, username, role).setVisible(true);
    }//GEN-LAST:event_btnReturnToDashboardActionPerformed

    private void chckbtnShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbtnShowPasswordActionPerformed
        txtPassword.setEchoChar(chckbtnShowPassword.isSelected() ? (char) 0 : '*');
    }//GEN-LAST:event_chckbtnShowPasswordActionPerformed

    private void loadUserData() {
        String sql = "SELECT username, role, gender, birthday, password FROM users WHERE id = ?";
        Connection connect = DatabaseConnection.getConnection();

        if (connect == null) {
            JOptionPane.showMessageDialog(this,
                    "Cannot connect to database.",
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (PreparedStatement statement = connect.prepareStatement(sql)) {
            statement.setInt(1, userID);

            ResultSet setResult = statement.executeQuery();

            if (setResult.next()) {
                lblHello_Acc.setText("Hello - " + setResult.getString("username"));
                jLabel1.setText(setResult.getString("username"));

                txtUsername.setText(setResult.getString("username"));
                txtUsername.setEditable(false);

                lblWhatRole.setText(setResult.getString("role"));

                String gender = setResult.getString("gender");
                String birthday = setResult.getString("birthday");

                lblWhatGender.setText(gender != null ? gender : "Not set");
                lblWhatBirthdate.setText(birthday != null ? birthday : "Not set");

                txtPassword.setText(setResult.getString("password"));
            }

        } catch (SQLException e) {
            logger.severe("Load user data error: " + e.getMessage());
        }
    }

    private void applyTheme() {
        getContentPane().setBackground(AppTheme.BACKGROUND);

        pnlTop.setBackground(AppTheme.SURFACE);
        pnlTop.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, AppTheme.BORDER));
        LOGO.setForeground(AppTheme.ACCENT_GREEN);
        lblAccountManager.setFont(AppTheme.FONT_SUBTITLE);
        lblAccountManager.setForeground(AppTheme.TEXT_PRIMARY);
        lblHello_Acc.setFont(AppTheme.FONT_BODY);
        lblHello_Acc.setForeground(AppTheme.TEXT_MUTED);

        pnlSide.setBackground(AppTheme.SURFACE);
        pnlSide.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 1, AppTheme.BORDER));
        pnlSide.setPreferredSize(new Dimension(165, 0));
        jLabel1.setFont(AppTheme.FONT_HEADER);
        jLabel1.setForeground(AppTheme.ACCENT_GREEN);
        lblWhatRole.setFont(AppTheme.FONT_SMALL);
        lblWhatRole.setForeground(AppTheme.TEXT_MUTED);
        AppTheme.styleSeparator(jSeparator1);
        AppTheme.styleSeparator(jSeparator2);
        jLabel4.setFont(AppTheme.FONT_HEADER);
        jLabel4.setForeground(AppTheme.ACCENT_GREEN);
        AppTheme.styleLabel(lblGender);
        AppTheme.styleLabelMuted(lblWhatGender);
        AppTheme.styleLabel(lblBirthdate);
        AppTheme.styleLabelMuted(lblWhatBirthdate);
        AppTheme.styleBtnDanger(btnLogOut);

        pnlMain.setBackground(AppTheme.BACKGROUND);
        pnlAccountInfo.setBackground(AppTheme.SURFACE);
        pnlAccountInfo.setBorder(AppTheme.paddedBorder(8));
        pnlPasswordInfo.setBackground(AppTheme.SURFACE);
        pnlPasswordInfo.setBorder(AppTheme.paddedBorder(8));

        AppTheme.styleLabelSubtitle(lblAccountInfo);
        AppTheme.styleLabelHeader(lblUsername);
        AppTheme.styleTextField(txtUsername);

        AppTheme.styleLabelSubtitle(lblPasswordInfo);
        AppTheme.stylePasswordField(txtPassword);
        AppTheme.styleCheckBox(chckbtnShowPassword);
        AppTheme.styleBtnSecondary(btnChangePassword);
        AppTheme.styleBtnSecondary(btnReturnToDashboard);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LogIn_Surface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGO;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnReturnToDashboard;
    private javax.swing.JCheckBox chckbtnShowPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAccountInfo;
    private javax.swing.JLabel lblAccountManager;
    private javax.swing.JLabel lblBirthdate;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHello_Acc;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordInfo;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblWhatBirthdate;
    private javax.swing.JLabel lblWhatGender;
    private javax.swing.JLabel lblWhatRole;
    private javax.swing.JPanel pnlAccountInfo;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlPasswordInfo;
    private javax.swing.JPanel pnlSide;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
