

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class AdminDashboard_Surface extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard_Surface.class.getName());

    private int adminID;
    private int selectedUserIDs = -1;
    private String adminsUsername;
    private String adminRole;

    private String holderSearch = "Search Username...";

    public AdminDashboard_Surface(int adminID, String adminsUsername, String adminRole) {
        this.adminID = adminID;
        this.adminsUsername = adminsUsername;
        this.adminRole = adminRole;

        initComponents();
        this.setLocationRelativeTo(null);

        this.setResizable(false);
        this.setMaximumSize(new java.awt.Dimension(920, 700));
        this.setMinimumSize(new java.awt.Dimension(920, 700));

        this.setTitle("Admin Dashboard - " + adminsUsername);

        loadAllUsers();
        loadSummary();

        txtInputSearchName.setText(holderSearch);
        txtInputSearchName.setForeground(Color.GRAY);

        tblUsers.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                loadSelectedUserTasks();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainDashboard = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        pnlContainer = new javax.swing.JPanel();
        lblAllUser = new javax.swing.JLabel();
        txtInputSearchName = new javax.swing.JTextField();
        btnSearchUsername = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTasks = new javax.swing.JTable();
        pnlContainer2 = new javax.swing.JPanel();
        lblUserTasks = new javax.swing.JLabel();
        lblTasksFor = new javax.swing.JLabel();
        pnlTitle = new javax.swing.JPanel();
        lblAdminDashboard = new javax.swing.JLabel();
        lblLoggedAs = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(920, 650));

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "#", "Id", "Username", "Role", "Gender", "Birthday"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsers.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblUsers);
        tblUsers.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblUsers.getColumnModel().getColumnCount() > 0) {
            tblUsers.getColumnModel().getColumn(0).setResizable(false);
            tblUsers.getColumnModel().getColumn(1).setResizable(false);
            tblUsers.getColumnModel().getColumn(2).setResizable(false);
            tblUsers.getColumnModel().getColumn(3).setResizable(false);
            tblUsers.getColumnModel().getColumn(4).setResizable(false);
            tblUsers.getColumnModel().getColumn(5).setResizable(false);
        }

        lblAllUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAllUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAllUser.setText("All Users");

        txtInputSearchName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtInputSearchName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtInputSearchName.setText("Search username...");
        txtInputSearchName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInputSearchNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInputSearchNameFocusLost(evt);
            }
        });

        btnSearchUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSearchUsername.setText("Search");
        btnSearchUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchUsernameActionPerformed(evt);
            }
        });

        btnRefresh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnDeleteUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDeleteUser.setText("Delete User");
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlContainerLayout = new javax.swing.GroupLayout(pnlContainer);
        pnlContainer.setLayout(pnlContainerLayout);
        pnlContainerLayout.setHorizontalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAllUser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInputSearchName, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlContainerLayout.setVerticalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAllUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInputSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Subject", "Task Title", "Deadline", "Status", "Days Left"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTasks.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(tblTasks);
        tblTasks.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblTasks.getColumnModel().getColumnCount() > 0) {
            tblTasks.getColumnModel().getColumn(0).setResizable(false);
            tblTasks.getColumnModel().getColumn(1).setResizable(false);
            tblTasks.getColumnModel().getColumn(2).setResizable(false);
            tblTasks.getColumnModel().getColumn(3).setResizable(false);
            tblTasks.getColumnModel().getColumn(4).setResizable(false);
        }

        lblUserTasks.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUserTasks.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUserTasks.setText("User Tasks");

        lblTasksFor.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblTasksFor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTasksFor.setText("Tasks for:");

        javax.swing.GroupLayout pnlContainer2Layout = new javax.swing.GroupLayout(pnlContainer2);
        pnlContainer2.setLayout(pnlContainer2Layout);
        pnlContainer2Layout.setHorizontalGroup(
            pnlContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainer2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUserTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTasksFor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlContainer2Layout.setVerticalGroup(
            pnlContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContainer2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserTasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTasksFor, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlMainDashboardLayout = new javax.swing.GroupLayout(pnlMainDashboard);
        pnlMainDashboard.setLayout(pnlMainDashboardLayout);
        pnlMainDashboardLayout.setHorizontalGroup(
            pnlMainDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(pnlMainDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlContainer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlMainDashboardLayout.setVerticalGroup(
            pnlMainDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContainer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pnlMainDashboard, java.awt.BorderLayout.CENTER);

        lblAdminDashboard.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblAdminDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAdminDashboard.setText("Admin's Dashboard");

        lblLoggedAs.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLoggedAs.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLoggedAs.setText("Logged in as:");

        btnLogOut.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdminDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
                    .addGroup(pnlTitleLayout.createSequentialGroup()
                        .addComponent(lblLoggedAs, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAdminDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLoggedAs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlTitleLayout.createSequentialGroup()
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        getContentPane().add(pnlTitle, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        //Logs Out, and shift into the Log In System
        dispose();
        new LogIn_Surface().setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void txtInputSearchNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputSearchNameFocusGained
        if (txtInputSearchName.getText().equals(holderSearch)) {
            txtInputSearchName.setText("");
            txtInputSearchName.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtInputSearchNameFocusGained

    private void txtInputSearchNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputSearchNameFocusLost
        if (txtInputSearchName.getText().trim().isEmpty()) {
            txtInputSearchName.setText(holderSearch);
            txtInputSearchName.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtInputSearchNameFocusLost

    private void btnSearchUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchUsernameActionPerformed
        loadAllUsers();
    }//GEN-LAST:event_btnSearchUsernameActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        txtInputSearchName.setText(holderSearch);
        txtInputSearchName.setForeground(Color.GRAY);
        loadAllUsers();
        loadSummary();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        deleteUser();
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void loadAllUsers() {
        DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
        model.setRowCount(0);

        selectedUserIDs = -1;

        String searchInput = txtInputSearchName.getText().trim();

        boolean isSearching = !searchInput.isEmpty() && !searchInput.equals(holderSearch);

        StringBuilder sql = new StringBuilder("SELECT id, username, role, gender, birthday FROM users");
        if (isSearching) {
            sql.append(" WHERE username LIKE ?");
        }
        sql.append(" ORDER BY id ASC");

        Connection connect = DatabaseConnection.getConnection();
        if (connect == null) {
            JOptionPane.showMessageDialog(this,
                    "Cannot connect to database.",
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (PreparedStatement stmt = connect.prepareStatement(sql.toString())) {
            if (isSearching) {
                stmt.setString(1, "%" + searchInput + "%");
            }

            ResultSet rs = stmt.executeQuery();
            int rowNum = 1;
            while (rs.next()) {
                int id = rs.getInt("id");
                String uname = rs.getString("username");
                String role = rs.getString("role");
                String gender = rs.getString("gender");
                String birthday = rs.getString("birthday");

                model.addRow(new Object[]{
                    rowNum,
                    id,
                    uname,
                    role,
                    gender != null ? gender : "N/A",
                    birthday != null ? birthday : "N/A"
                });

                tblUsers.putClientProperty("uid_" + (rowNum - 1), id);
                rowNum++;
            }

        } catch (SQLException e) {
            logger.severe("Load users error: " + e.getMessage());
            showErr("Error loading users: " + e.getMessage());
        }

        ((DefaultTableModel) tblTasks.getModel()).setRowCount(0);
        lblTasksFor.setText("Tasks — select a user above to view their tasks");

    }

    private void loadSelectedUserTasks() {
        int row = tblUsers.getSelectedRow();
        if (row < 0) {
            return;
        }

        Object id = tblUsers.getClientProperty("uid_" + row);
        if (id == null) {
            return;
        }

        selectedUserIDs = (int) id;

        String selectedUser = (String) tblUsers.getValueAt(row, 2);
        lblTasksFor.setText("Tasks for: " + selectedUser + "  (id=" + selectedUserIDs + ")");

        DefaultTableModel model = (DefaultTableModel) tblTasks.getModel();
        model.setRowCount(0);

        String sql = "SELECT id, subject, title, deadline, status FROM tasks " + "WHERE user_id = ? ORDER BY deadline ASC";

        Connection connect = DatabaseConnection.getConnection();
        if (connect == null) {
            JOptionPane.showMessageDialog(this,
                    "Cannot connect to database.",
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (PreparedStatement stmt = connect.prepareStatement(sql)) {
            stmt.setInt(1, selectedUserIDs);
            ResultSet rs = stmt.executeQuery();
            int rowNum = 1;

            while (rs.next()) {
                String deadline = rs.getString("deadline");
                long daysLeft = daysLeft(deadline);
                String status = rs.getString("status");

                if (daysLeft < 0 && !status.equals("Done/Checked")
                        && !status.equals("Submitted")) {
                    status = "Overdue";
                }

                model.addRow(new Object[]{
                    rs.getString("subject"),
                    rs.getString("title"),
                    deadline,
                    status,
                    daysLeft
                });
            }

        } catch (SQLException e) {
            logger.severe("Load tasks error: " + e.getMessage());
            showErr("Error loading tasks: " + e.getMessage());
        }

    }

    private void loadSummary() {
        Connection connect = DatabaseConnection.getConnection();
        if (connect == null) {
            JOptionPane.showMessageDialog(this,
                    "Cannot connect to database.",
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            ResultSet rs1 = connect.createStatement()
                    .executeQuery("SELECT COUNT(*) FROM users");
            ResultSet rs2 = connect.createStatement()
                    .executeQuery("SELECT COUNT(*) FROM tasks");
            ResultSet rs3 = connect.createStatement()
                    .executeQuery("SELECT COUNT(*) FROM tasks WHERE status = 'Overdue'");

            int totalUsers = rs1.next() ? rs1.getInt(1) : 0;
            int totalTasks = rs2.next() ? rs2.getInt(1) : 0;
            int overdue = rs3.next() ? rs3.getInt(1) : 0;

            lblLoggedAs.setText("Logged in as: " + adminsUsername
                    + "   |   Users: " + totalUsers
                    + "   Tasks: " + totalTasks
                    + "   Overdue: " + overdue);

        } catch (SQLException e) {
            logger.warning("Summary load error: " + e.getMessage());
        }
    }

    private void deleteUser() {
        if (selectedUserIDs == -1) {
            showWarn("Please select a user from the table first.");
            return;
        }

        if (selectedUserIDs == adminID) {
            showWarn("You cannot delete your own admin account.");
            return;
        }

        int row = tblUsers.getSelectedRow();
        String targetUsername = (String) tblUsers.getValueAt(row, 2);
        String targetRole = (String) tblUsers.getValueAt(row, 3);

        if ("admin".equalsIgnoreCase(targetRole)) {
            showWarn("Cannot delete another admin account.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Delete user \"" + targetUsername + "\" and ALL their tasks?\nThis cannot be undone.",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        String sql = "DELETE FROM users WHERE id = ?";
        Connection connect = DatabaseConnection.getConnection();

        if (connect == null) {
            JOptionPane.showMessageDialog(this,
                    "Cannot connect to database.",
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (PreparedStatement stmt = connect.prepareStatement(sql)) {
            stmt.setInt(1, selectedUserIDs);
            int rows = stmt.executeUpdate();

            if (rows > 0) {
                JOptionPane.showMessageDialog(this,
                        "User \"" + targetUsername + "\" deleted successfully.",
                        "Deleted", JOptionPane.INFORMATION_MESSAGE);
                selectedUserIDs = -1;
                loadAllUsers();  // refresh both tables
                loadSummary();   // refresh the counts
            } else {
                showErr("Delete failed — user not found.");
            }

        } catch (SQLException e) {
            logger.severe("Delete user error: " + e.getMessage());
            showErr("Error deleting user: " + e.getMessage());
        }

    }

    private long daysLeft(String deadlineStr) {
        try {
            return ChronoUnit.DAYS.between(
                    LocalDate.now(),
                    LocalDate.parse(deadlineStr)
            );
        } catch (Exception e) {
            return 0;
        }
    }

    private void showErr(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Error", JOptionPane.ERROR_MESSAGE);
    }

    private void showWarn(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Warning", JOptionPane.WARNING_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LogIn_Surface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearchUsername;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAdminDashboard;
    private javax.swing.JLabel lblAllUser;
    private javax.swing.JLabel lblLoggedAs;
    private javax.swing.JLabel lblTasksFor;
    private javax.swing.JLabel lblUserTasks;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlContainer2;
    private javax.swing.JPanel pnlMainDashboard;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JTable tblTasks;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtInputSearchName;
    // End of variables declaration//GEN-END:variables
}
