package mysystem;

import java.awt.CardLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class LogIn_Surface extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LogIn_Surface.class.getName());

    /*
    Installed Account in the System:
    
        Username: AdminAcc
        Password: admin1234
        role: admin
    
     */
    private CardLayout layout;

    private int loggedInUserID = -1;
    private String loggedInUsername = "";

    private static final String placeholderUsername = "Enter username";
    private static final String placeholderPassword = "Enter password";

    public LogIn_Surface() {
        initComponents();

        //This shows the output in the center
        this.setLocationRelativeTo(null);

        //Sets the size to be untangleable and in fixed size
        this.setResizable(false);
        this.setMinimumSize(new java.awt.Dimension(500, 450));
        this.setMaximumSize(new java.awt.Dimension(500, 450));
        this.setPreferredSize(new java.awt.Dimension(500, 450));

        //Sets the title to LogIn
        this.setTitle("Log In");

        layout = (CardLayout) pnlMain.getLayout();

        //Makes the about info uneditable
        txtaAbout.setEditable(false);

        //Sets placeholder text for both username and password
        txtInputUsername.setText(placeholderUsername);
        txtInputUsername.setForeground(Color.GRAY);

        txtInputPassword.setText(placeholderPassword);
        txtInputPassword.setEchoChar((char) 0);
        txtInputPassword.setForeground(Color.GRAY);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlSide = new javax.swing.JPanel();
        LOGO = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblHomework = new javax.swing.JLabel();
        btnAbout = new javax.swing.JButton();
        lblTracker = new javax.swing.JLabel();
        lblSystem = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        pnlMain = new javax.swing.JPanel();
        pnlLogIn = new javax.swing.JPanel();
        lblWelcomeMSG = new javax.swing.JLabel();
        lblSignInMSG = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtInputUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtInputPassword = new javax.swing.JPasswordField();
        chckbtnShowPassword = new javax.swing.JCheckBox();
        btnLogIn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblNoAccountYet = new javax.swing.JLabel();
        btnGoToSignUp = new javax.swing.JButton();
        pnlAbout = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaAbout = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 450));
        setMinimumSize(new java.awt.Dimension(500, 450));
        setSize(new java.awt.Dimension(500, 450));

        pnlSide.setMaximumSize(new java.awt.Dimension(160, 450));
        pnlSide.setMinimumSize(new java.awt.Dimension(160, 450));

        LOGO.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        LOGO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGO.setText("LOGO");

        lblHomework.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHomework.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHomework.setText("Homework");

        btnAbout.setText("About");
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });

        lblTracker.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTracker.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTracker.setText("Tracker");

        lblSystem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSystem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSystem.setText("System");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout pnlSideLayout = new javax.swing.GroupLayout(pnlSide);
        pnlSide.setLayout(pnlSideLayout);
        pnlSideLayout.setHorizontalGroup(
            pnlSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHomework, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(lblTracker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSystem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAbout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(LOGO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlSideLayout.setVerticalGroup(
            pnlSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSideLayout.createSequentialGroup()
                        .addComponent(LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHomework)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTracker)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSystem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                        .addComponent(btnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3))
                .addContainerGap())
        );

        getContentPane().add(pnlSide, java.awt.BorderLayout.LINE_START);

        pnlMain.setMaximumSize(new java.awt.Dimension(340, 450));
        pnlMain.setMinimumSize(new java.awt.Dimension(340, 450));
        pnlMain.setPreferredSize(new java.awt.Dimension(340, 450));
        pnlMain.setLayout(new java.awt.CardLayout());

        pnlLogIn.setMaximumSize(new java.awt.Dimension(340, 450));
        pnlLogIn.setMinimumSize(new java.awt.Dimension(340, 450));
        pnlLogIn.setPreferredSize(new java.awt.Dimension(340, 450));
        pnlLogIn.setLayout(new java.awt.GridBagLayout());

        lblWelcomeMSG.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblWelcomeMSG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomeMSG.setText("Welcome Back!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 18;
        pnlLogIn.add(lblWelcomeMSG, gridBagConstraints);

        lblSignInMSG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSignInMSG.setText("Sign in to your account");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        pnlLogIn.add(lblSignInMSG, gridBagConstraints);

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsername.setText("USERNAME");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        pnlLogIn.add(lblUsername, gridBagConstraints);

        txtInputUsername.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtInputUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInputUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInputUsernameFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        pnlLogIn.add(txtInputUsername, gridBagConstraints);

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPassword.setText("PASSWORD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        pnlLogIn.add(lblPassword, gridBagConstraints);

        txtInputPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtInputPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInputPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInputPasswordFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 0);
        pnlLogIn.add(txtInputPassword, gridBagConstraints);

        chckbtnShowPassword.setText("Show password");
        chckbtnShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckbtnShowPasswordActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 12, 0);
        pnlLogIn.add(chckbtnShowPassword, gridBagConstraints);

        btnLogIn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogIn.setText("Log In");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        pnlLogIn.add(btnLogIn, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(13, 0, 12, 0);
        pnlLogIn.add(jSeparator1, gridBagConstraints);

        lblNoAccountYet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNoAccountYet.setText("No account yet?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        pnlLogIn.add(lblNoAccountYet, gridBagConstraints);

        btnGoToSignUp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGoToSignUp.setText("Go to Sign Up");
        btnGoToSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToSignUpActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 10;
        pnlLogIn.add(btnGoToSignUp, gridBagConstraints);

        pnlMain.add(pnlLogIn, "pnlLogIn");

        pnlAbout.setMaximumSize(new java.awt.Dimension(340, 450));
        pnlAbout.setMinimumSize(new java.awt.Dimension(340, 450));
        pnlAbout.setPreferredSize(new java.awt.Dimension(340, 450));

        txtaAbout.setColumns(20);
        txtaAbout.setRows(5);
        jScrollPane1.setViewportView(txtaAbout);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("About");

        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAboutLayout = new javax.swing.GroupLayout(pnlAbout);
        pnlAbout.setLayout(pnlAboutLayout);
        pnlAboutLayout.setHorizontalGroup(
            pnlAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAboutLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlAboutLayout.setVerticalGroup(
            pnlAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlMain.add(pnlAbout, "pnlAbout");

        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        //Gets the user input and converts it to String
        String username = txtInputUsername.getText().trim();
        String password = new String(txtInputPassword.getPassword()).trim();

        if (username.equals(placeholderUsername)) {
            username = "";
        }
        
        if (password.equals(placeholderPassword)) {
            password = "";
        }
        
        //Checks if username and password input is empty
        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please enter both username and password.",
                    "Missing Fields",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Checks if role is user/admin
        String role = checkCredentials(username, password);

        if (role == null) {
            JOptionPane.showMessageDialog(this,
                    "Invalid username or password.",
                    "Login Failed",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            dispose();
            if ("admin".equalsIgnoreCase(role)) {
                new AdminDashboard_Surface(loggedInUserID, loggedInUsername, role).setVisible(true);
            } else {
                new HomeworkTrackerSystem(loggedInUserID, loggedInUsername, role).setVisible(true);
            }

        }

    }//GEN-LAST:event_btnLogInActionPerformed

    private void btnGoToSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToSignUpActionPerformed
        //Closes this window and go to SignUp_Surface window
        dispose();
        new SignUp_Surface().setVisible(true);

    }//GEN-LAST:event_btnGoToSignUpActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        // TODO add your handling code here:
        layout.show(pnlMain, "pnlAbout");

    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:\
        layout.show(pnlMain, "pnlLogIn");
    }//GEN-LAST:event_btnReturnActionPerformed

    private void chckbtnShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbtnShowPasswordActionPerformed
        //Shows or Hide the password when check
        txtInputPassword.setEchoChar(chckbtnShowPassword.isSelected() ? (char) 0 : '\u2022');
    }//GEN-LAST:event_chckbtnShowPasswordActionPerformed

    private void txtInputUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputUsernameFocusGained
        //Makes the input username text be empty when gained focus
        if (txtInputUsername.getText().equals(placeholderUsername)) {
            txtInputUsername.setText("");
            txtInputUsername.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtInputUsernameFocusGained

    private void txtInputUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputUsernameFocusLost
        //Makes the input username text contain the "Enter username" message when lost focus

        if (txtInputUsername.getText().trim().isEmpty()) {
            txtInputUsername.setText(placeholderUsername);
            txtInputUsername.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtInputUsernameFocusLost

    private void txtInputPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputPasswordFocusGained
        //Makes the input password text be empty when gained focus
        if (new String(txtInputPassword.getPassword()).equals(placeholderPassword)) {
            txtInputPassword.setText("");
            txtInputPassword.setEchoChar('\u2022');
            txtInputPassword.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtInputPasswordFocusGained

    private void txtInputPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputPasswordFocusLost
        //Makes the input username text contain the "Enter username" message when lost focus
        if (new String(txtInputPassword.getPassword()).trim().isEmpty()) {
            txtInputPassword.setText(placeholderPassword);
            txtInputPassword.setEchoChar((char) 0);
            txtInputPassword.setForeground(Color.GRAY);

            chckbtnShowPassword.setSelected(false);
        }
    }//GEN-LAST:event_txtInputPasswordFocusLost

    private String checkCredentials(String username, String password) {
        //Checks if the user input is within the system or not
        String sql = "SELECT id, role FROM users WHERE username = ? AND password = ?";
        Connection connect = DatabaseConnection.getConnection();

        if (connect == null) {
            JOptionPane.showMessageDialog(this,
                    "Cannot connect to database.",
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE);
            return null;
        }

        try (PreparedStatement statement = connect.prepareStatement(sql)) {
            statement.setString(1, username);
            statement.setString(2, password);

            ResultSet setResult = statement.executeQuery();

            if (setResult.next()) {
                loggedInUserID = setResult.getInt("id"); //Saves user ID
                loggedInUsername = username; //Saves username

                return setResult.getString("role"); //Checks whether an "admin" or "user"
            }

        } catch (SQLException e) {
            logger.severe("Login error: " + e.getMessage());
        }
        return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LogIn_Surface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGO;
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnGoToSignUp;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnReturn;
    private javax.swing.JCheckBox chckbtnShowPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblHomework;
    private javax.swing.JLabel lblNoAccountYet;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSignInMSG;
    private javax.swing.JLabel lblSystem;
    private javax.swing.JLabel lblTracker;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblWelcomeMSG;
    private javax.swing.JPanel pnlAbout;
    private javax.swing.JPanel pnlLogIn;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlSide;
    private javax.swing.JPasswordField txtInputPassword;
    private javax.swing.JTextField txtInputUsername;
    private javax.swing.JTextArea txtaAbout;
    // End of variables declaration//GEN-END:variables
}
