package mysystem;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class SignUp_Surface extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignUp_Surface.class.getName());

    private String holderUsername = "Aisa";
    private String holderPass = "aisa1234";

    public SignUp_Surface() {
        initComponents();

        //This shows the output in the center
        this.setLocationRelativeTo(null);

        //Sets the size to be untangleable and in fixed size
        this.setResizable(false);
        this.setMinimumSize(new java.awt.Dimension(500, 450));
        this.setMaximumSize(new java.awt.Dimension(500, 450));
        this.setPreferredSize(new java.awt.Dimension(500, 450));

        //Sets title to Sign Up
        this.setTitle("Sign Up");

        //Fixes the jSpinner to show the proper format MM-DD-YYYY
        spnSelectBirthday.setEditor(new javax.swing.JSpinner.DateEditor(spnSelectBirthday, "MM-dd-yyyy"));

        //Sets placeholders
        txtInputUsername.setText(holderUsername);
        txtInputUsername.setForeground(Color.GRAY);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngGender = new javax.swing.ButtonGroup();
        SignUpPanel = new javax.swing.JPanel();
        LOGO = new javax.swing.JLabel();
        lblCreateMSG = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblRegisterMSG = new javax.swing.JLabel();
        pnlSignUp = new javax.swing.JPanel();
        txtInputUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        lblBirthday = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtInputPassword = new javax.swing.JPasswordField();
        chckbtnShowPassword = new javax.swing.JCheckBox();
        lblGender = new javax.swing.JLabel();
        rbtnFemale = new javax.swing.JRadioButton();
        rbtnMale = new javax.swing.JRadioButton();
        spnSelectBirthday = new javax.swing.JSpinner();
        btnCreateAccount = new javax.swing.JButton();
        btnGoToLogIn = new javax.swing.JButton();
        lblAlreadyHaveAnAccount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 450));
        setMinimumSize(new java.awt.Dimension(500, 450));
        setSize(new java.awt.Dimension(500, 450));

        SignUpPanel.setMaximumSize(new java.awt.Dimension(500, 450));
        SignUpPanel.setMinimumSize(new java.awt.Dimension(500, 450));
        SignUpPanel.setPreferredSize(new java.awt.Dimension(500, 450));

        LOGO.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        LOGO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGO.setText("LOGO");

        lblCreateMSG.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCreateMSG.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCreateMSG.setText("Create Account");

        lblRegisterMSG.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRegisterMSG.setText("Register your account");

        pnlSignUp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        txtInputUsername.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtInputUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInputUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInputUsernameFocusLost(evt);
            }
        });

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPassword.setText("PASSWORD");

        lblBirthday.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBirthday.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBirthday.setText("BIRTHDAY");

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsername.setText("USERNAME");

        txtInputPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtInputPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInputPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInputPasswordFocusLost(evt);
            }
        });

        chckbtnShowPassword.setText("Show password");
        chckbtnShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckbtnShowPasswordActionPerformed(evt);
            }
        });

        lblGender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGender.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGender.setText("GENDER");

        btngGender.add(rbtnFemale);
        rbtnFemale.setText("Female");

        btngGender.add(rbtnMale);
        rbtnMale.setText("Male");

        spnSelectBirthday.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(788926260000L), null, java.util.Calendar.MONTH));

        btnCreateAccount.setText("Create Account");
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSignUpLayout = new javax.swing.GroupLayout(pnlSignUp);
        pnlSignUp.setLayout(pnlSignUpLayout);
        pnlSignUpLayout.setHorizontalGroup(
            pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSignUpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtInputUsername)
                    .addComponent(txtInputPassword)
                    .addGroup(pnlSignUpLayout.createSequentialGroup()
                        .addComponent(chckbtnShowPassword)
                        .addGap(37, 37, 37)
                        .addComponent(lblBirthday)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnSelectBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 144, Short.MAX_VALUE))
                    .addGroup(pnlSignUpLayout.createSequentialGroup()
                        .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername)
                            .addComponent(lblPassword)
                            .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(rbtnMale, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblGender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(rbtnFemale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlSignUpLayout.setVerticalGroup(
            pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSignUpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chckbtnShowPassword)
                    .addComponent(lblBirthday)
                    .addComponent(spnSelectBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSignUpLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(rbtnFemale)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSignUpLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblGender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnMale)
                        .addGap(16, 16, 16)
                        .addComponent(btnCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        btnGoToLogIn.setText("Go to Log In");
        btnGoToLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToLogInActionPerformed(evt);
            }
        });

        lblAlreadyHaveAnAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlreadyHaveAnAccount.setText("Already have an account?");

        javax.swing.GroupLayout SignUpPanelLayout = new javax.swing.GroupLayout(SignUpPanel);
        SignUpPanel.setLayout(SignUpPanelLayout);
        SignUpPanelLayout.setHorizontalGroup(
            SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpPanelLayout.createSequentialGroup()
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SignUpPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(SignUpPanelLayout.createSequentialGroup()
                                .addComponent(LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCreateMSG, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                                    .addComponent(lblRegisterMSG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(SignUpPanelLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAlreadyHaveAnAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(SignUpPanelLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(btnGoToLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SignUpPanelLayout.setVerticalGroup(
            SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignUpPanelLayout.createSequentialGroup()
                        .addComponent(lblCreateMSG, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRegisterMSG, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addComponent(LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAlreadyHaveAnAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGoToLogIn)
                .addContainerGap())
        );

        getContentPane().add(SignUpPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        //Creates account
        String username = txtInputUsername.getText().trim();
        String password = new String(txtInputPassword.getPassword()).trim();

        //Checks if username and password input is empty
        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please fill all fields.",
                    "Missing Fields",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Checks if username is less than 4 character
        if (username.length() < 4) {
            JOptionPane.showMessageDialog(this,
                    "Username must be at least 4 characters.",
                    "Invalid Username",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        //Checks if password is less than 6 character
        if (password.length() < 6) {
            JOptionPane.showMessageDialog(this,
                    "Password must be at least 6 characters.",
                    "Weak Password",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        //Checks if a gender is selected or not
        if (!rbtnMale.isSelected() && !rbtnFemale.isSelected()) {
            JOptionPane.showMessageDialog(this,
                    "Please select a gender.",
                    "Missing Gender",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        registerUser(username, password);

    }//GEN-LAST:event_btnCreateAccountActionPerformed

    private void btnGoToLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToLogInActionPerformed
        //Closes this window and open the LogIn window
        dispose();
        new LogIn_Surface().setVisible(true);
    }//GEN-LAST:event_btnGoToLogInActionPerformed

    private void chckbtnShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbtnShowPasswordActionPerformed
        txtInputPassword.setEchoChar(chckbtnShowPassword.isSelected() ? (char) 0 : '*');
    }//GEN-LAST:event_chckbtnShowPasswordActionPerformed

    private void txtInputUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputUsernameFocusGained
        if (txtInputUsername.getText().equals(holderUsername)) {
            txtInputUsername.setText("");
            txtInputUsername.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtInputUsernameFocusGained

    private void txtInputUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputUsernameFocusLost
        if (txtInputUsername.getText().trim().isEmpty()) {
            txtInputUsername.setText(holderUsername);
            txtInputUsername.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtInputUsernameFocusLost

    private void txtInputPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputPasswordFocusGained
        if (new String(txtInputPassword.getPassword()).equals(holderPass)) {
            txtInputPassword.setText("");
            txtInputPassword.setEchoChar('*');
            txtInputPassword.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtInputPasswordFocusGained

    private void txtInputPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputPasswordFocusLost
        if (new String(txtInputPassword.getPassword()).trim().isEmpty()) {
            txtInputPassword.setText(holderPass);
            txtInputPassword.setEchoChar((char) 0);
            txtInputPassword.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtInputPasswordFocusLost

    private void registerUser(String username, String password) {
        //Database registration
        String checkSQL = "SELECT id FROM users WHERE username = ?";
        String insertSQL = "INSERT INTO users (username, password, role, gender, birthday) VALUES (?, ?, 'user', ?, ?)";
        Connection connect = DatabaseConnection.getConnection();

        if (connect == null) {
            JOptionPane.showMessageDialog(this,
                    "Cannot connect to database.",
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            //Checks if username is already taken or not
            PreparedStatement checks = connect.prepareStatement(checkSQL);
            checks.setString(1, username);

            ResultSet setResult = checks.executeQuery();

            if (setResult.next()) {
                JOptionPane.showMessageDialog(this,
                        "Username \"" + username + "\"is already taken. \nPlease choose a different one.",
                        "Username Taken",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            //Identifies the gender selected
            String gender = "Not set";
            if (rbtnMale.isSelected()) {
                gender = "Male";
            } else if (rbtnFemale.isSelected()) {
                gender = "Female";
            }

            //Gets the user's birthday
            java.util.Date selectedDate = (java.util.Date) spnSelectBirthday.getValue();
            java.text.SimpleDateFormat dateFormat = new java.text.SimpleDateFormat("MM-dd-yyyy");
            String birthday = dateFormat.format(selectedDate);

            //Inserts a new user with 'user' role
            PreparedStatement inserts = connect.prepareStatement(insertSQL);
            inserts.setString(1, username);
            inserts.setString(2, password);
            inserts.setString(3, gender);
            inserts.setString(4, birthday);
            inserts.executeUpdate();

            JOptionPane.showMessageDialog(this,
                    "Account created successfully! \nYou can now log in.",
                    "Sign Up Successful",
                    JOptionPane.INFORMATION_MESSAGE);

            //Return to LogIn_Surface after successfully register an account
            dispose();
            new LogIn_Surface().setVisible(true);

        } catch (SQLException e) {
            logger.severe("Sign-up error: " + e.getMessage());
            JOptionPane.showMessageDialog(this,
                    "Database Error: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LogIn_Surface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGO;
    private javax.swing.JPanel SignUpPanel;
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JButton btnGoToLogIn;
    private javax.swing.ButtonGroup btngGender;
    private javax.swing.JCheckBox chckbtnShowPassword;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAlreadyHaveAnAccount;
    private javax.swing.JLabel lblBirthday;
    private javax.swing.JLabel lblCreateMSG;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRegisterMSG;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlSignUp;
    private javax.swing.JRadioButton rbtnFemale;
    private javax.swing.JRadioButton rbtnMale;
    private javax.swing.JSpinner spnSelectBirthday;
    private javax.swing.JPasswordField txtInputPassword;
    private javax.swing.JTextField txtInputUsername;
    // End of variables declaration//GEN-END:variables
}
